/*
 * File: gruposLDAPStore.js
 * Date: Thu Dec 29 2011 13:06:30 GMT-0600 (Hora estÃ¡ndar de MÃ©xico)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

//Todos los campos con un '+' fuerón añadidos posteriormente a Ext Designer

gruposLDAPStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        gruposLDAPStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'gruposLDAPStore',
            url: '../LDAPServlet?action=obtenerGrupos', //+ Usar este en producción
            // url: '../js/gruposLDAP/grupos.json', //+ Usar para pruebas si no se cuenta con acceso a un servidor LDAP
            root: 'grupos',
            fields: ['name'] //+
        }, cfg));
    }
});
new gruposLDAPStore();