/*
 * File: MyViewport.ui.js
 * Date: Thu Dec 29 2011 13:06:30 GMT-0600 (Hora estÃ¡ndar de MÃ©xico)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

//Todos los campos con un '+' fuerón añadidos posteriormente a Ext Designer

MyViewportUi = Ext.extend(Ext.Viewport, {
	layout: 'absolute',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Privilegios del Grupo',
                width: 632,
                height: 317,
                layout: 'absolute',
                x: 20,
                y: 20,
                items: [
                    {
                        xtype: 'label',
                        text: 'Grupo de LDAP:',
                        x: 10,
                        y: 0
                    },
                    {
                        xtype: 'combo',
                        title: 'Grupos de LDAP',
                        store: Ext.StoreMgr.lookup('gruposLDAPStore'), //+
                        triggerAction: 'all',
                        mode: 'local', //+
                        emptyText: 'Escoja un grupo de LDAP (pueden que aun falta para que carguen)...',
                        displayField: "name", //+
                        valueField: "name", //+
                        editable: false,
                        x: 130,
                        y: 0,
                        width: 400,
                        listeners:  //+
                        { select: { fn:function(combo, value)
                              {
                        		Ext.StoreMgr.lookup('gavetasNoAsignadasStore').removeAll();
                                Ext.StoreMgr.lookup('gavetasNoAsignadasStore').reload({params:{grupo: this.value}});
                                
                                Ext.StoreMgr.lookup('gavetasAsignadasStore').removeAll();
                                Ext.StoreMgr.lookup('gavetasAsignadasStore').reload({params:{grupo: this.value}});
                              }
                        }  }
                    },
                    {
                        xtype: 'grid',
                        title: 'Gavetas no Asignadas',
                        x: 10,
                        y: 50,
                        height: 200,
                        width: 200,
                        store: Ext.StoreMgr.lookup('gavetasNoAsignadasStore'), //+
                        mode: 'local', //+
                        multiSelect: true, //+
                        hideHeaders: true,
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'name',
                                width: 196,
                                resizable: false,
                                editable: false
                            }
                        ]
                    },
                    {
                        xtype: 'grid',
                        title: 'Gavetas Asignadas',
                        x: 310,
                        y: 50,
                        height: 200,
                        width: 200,
                        store: Ext.StoreMgr.lookup('gavetasAsignadasStore'), //+
                        mode: 'local', //+
                        multiSelect: true, //+
                        hideHeaders: true,
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'name',
                                width: 196,
                                resizable: false,
                                editable: false
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Propiedades',
                        width: 102,
                        height: 160,
                        x: 520,
                        y: 50,
                        items: [
                            {
                                xtype: 'checkbox',
                                boxLabel: 'Eliminar'
                            },
                            {
                                xtype: 'checkbox',
                                boxLabel: 'Modificar'
                            },
                            {
                                xtype: 'checkbox',
                                boxLabel: 'Crear'
                            },
                            {
                                xtype: 'checkbox',
                                boxLabel: 'Imprimir'
                            },
                            {
                                xtype: 'checkbox',
                                boxLabel: 'Compartir'
                            },
                            {
                                xtype: 'checkbox',
                                boxLabel: 'Digitalizar'
                            },
                            {
                                xtype: 'checkbox',
                                boxLabel: 'Descargar'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        text: 'Asignar >>',
                        x: 220,
                        y: 120,
                        width: 80
                    },
                    {
                        xtype: 'button',
                        text: '<< Desasignar',
                        x: 220,
                        y: 160,
                        width: 80
                    },
                    {
                        xtype: 'button',
                        text: 'Actualizar Privilegios',
                        x: 200,
                        y: 260,
                        width: 120
                    }
                ]
            }
        ];
        MyViewportUi.superclass.initComponent.call(this);
    }
});
