/*
 * File: xds_index.js
 * Date: Thu Dec 29 2011 13:06:30 GMT-0600 (Hora estándar de México)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new MyViewport({
        renderTo: Ext.getBody()
    });
    cmp1.show();
    Ext.StoreMgr.lookup('gruposLDAPStore').removeAll(); //+
    Ext.StoreMgr.lookup('gruposLDAPStore').reload(); //+
});
